services:
  - type: web
    name: contafin
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: OLLAMA_URL
        value: https://evaenespanol.loca.lt
      - key: MODEL_NAME
        value: llama3:8b
      - key: PYTHON_VERSION
        value: 3.11.0