services:
  - type: web
    name: contafin
    env: docker
    plan: free
    envVars:
      - key: OLLAMA_URL
        value: https://evaenespanol.loca.lt
      - key: MODEL_NAME
        value: llama3:8b
      - key: FRONTEND_URL
        value: https://contafin-front.vercel.app
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
    domains:
      - contafin-api.onrender.com